// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZFNN3NYjfrryxscITOKFpz2S3TcKj8lg',
    appId: '1:488095132872:web:17464e63f884a349a009fd',
    messagingSenderId: '488095132872',
    projectId: 'instagram-clone-flutter-dac17',
    authDomain: 'instagram-clone-flutter-dac17.firebaseapp.com',
    storageBucket: 'instagram-clone-flutter-dac17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXBKoN-bd_hn4g70lbRuDXBb6bhRRuGwc',
    appId: '1:488095132872:android:417ed9b2b5884adba009fd',
    messagingSenderId: '488095132872',
    projectId: 'instagram-clone-flutter-dac17',
    storageBucket: 'instagram-clone-flutter-dac17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5GC8eBY5vzY0cXlDBaBM_361v7FtOys',
    appId: '1:488095132872:ios:8610d95b80581aaba009fd',
    messagingSenderId: '488095132872',
    projectId: 'instagram-clone-flutter-dac17',
    storageBucket: 'instagram-clone-flutter-dac17.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

}